/** Function that generates a value for each array position. */
type Filler<T = any> = (pos?: number) => T

/**
 * Creates an array of a specified length using a filler function.
 *
 * @param filler - Function called for each position to generate the array element.
 * @param length - Desired length of the array.
 * @returns A new array with elements generated by the filler function.
 */
export function make<T> (filler: Filler<T>, length: number) {
  return new Array(length)
    .fill(null)
    .map((_, pos) => filler(pos))
}
