export const disclaimer = 'lm-disclaimer'
export const eventListener = 'lm-event-listener'
export const input = 'lm-input'
export const intersectionObserver = 'lm-intersection-observer'
export const resizeObserver = 'lm-resize-observer'
